# Generated by Django 4.1.7 on 2023-02-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollerderbyapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
