# Generated by Django 4.1.7 on 2023-02-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rollerderbyapp', '0002_delete_quiz_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='year',
        ),
    ]
