# Generated by Django 4.1.7 on 2023-02-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollerderbyapp', '0003_remove_question_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='points',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='raisonnement',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='remarque',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='link_casebook',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
